export type ResidentLanguage = "en" | "zh" | "ms" | "ta";
export type MealDiet = "all" | "halal" | "vegetarian";

export const languages: { id: ResidentLanguage; label: string; speech: string }[] = [
  { id: "en", label: "English / Singlish", speech: "en-SG" },
  { id: "zh", label: "华语 / 福建话", speech: "zh-SG" },
  { id: "ms", label: "Bahasa Melayu", speech: "ms-MY" },
  { id: "ta", label: "தமிழ்", speech: "ta-IN" },
];

type Copy = { greeting: string; title: string; intro: string; demo: string; food: string; walk: string; cc: string; deals: string; placeholder: string; note: string; send: string; record: string; stop: string; diet: string; all: string; halal: string; vegetarian: string; empty: string; foodWarning: string; walkReply: string; otherReply: string; verifiedWarning: string; expired: string; withdrawn: string };

export const copy: Record<ResidentLanguage, Copy> = {
  en: {
    greeting: "Hello neighbour! Ask about lobang food, CC events, or find kakis for group activities.", title: "Ask about food, a message, or a walk.", intro: "Just send a message.", demo: "TRY A DEMO MESSAGE", food: "Meal Lobang", walk: "Find a group", cc: "CC & Kampung Events", deals: "Check for Live Deals", placeholder: "Type a message…", note: "Voice input uses your browser microphone. Review before sending.", send: "Send message", record: "Record a voice note", stop: "Stop recording", diet: "Meals I can eat", all: "All Meals", halal: "Halal", vegetarian: "Vegetarian / Vegan", empty: "No suitable checked meals right now. Please don't travel for an unchecked tip.", foodWarning: "This is only an unverified meal lobang. Please do not travel for it. A live stall photo, nearby location check and volunteer check are needed. Confirm price, availability and dietary suitability with the stall directly.", walkReply: "That sounds lovely. I don't have a live events list, so please ask your Community Club about their latest walking, dancerobics, wushu, karaoke or lunch groups before going. A volunteer can help you check.", otherReply: "Thank you for telling me. This is a demo, not a live help service. Please check with your local community centre. For immediate danger, call emergency services.", verifiedWarning: "A volunteer checked this meal in the demo. Please confirm it is still available and suits your diet with the stall before travelling. This is not an independent guarantee.", expired: "This meal listing has expired. Please do not travel for it.", withdrawn: "This meal listing is no longer available. Please do not travel for it."
  },
  zh: {
    greeting: "街坊你好！可以问优惠食物、民众俱乐部活动，或找伙伴参加小组活动。", title: "想问食物、短信，还是散步活动？", intro: "发个消息就好。", demo: "一按试试看", food: "食物消息", walk: "找活动小组", cc: "民众俱乐部活动", deals: "看看实时优惠", placeholder: "输入消息…", note: "语音由浏览器识别；发送前请检查文字。", send: "发送消息", record: "开始语音输入", stop: "停止录音", diet: "适合我的饮食", all: "所有餐食", halal: "清真", vegetarian: "素食 / 纯素", empty: "目前没有符合条件、经过检查的餐食。请勿为未经核实的消息出门。", foodWarning: "这只是未经核实的食物消息，请不要特地前往。需要现场照片、位置和义工检查。请直接向摊主确认价格、供应及饮食要求。", walkReply: "听起来不错！这里没有实时活动名单，出门前请向民众俱乐部查询最新的散步、健身操、武术或卡拉OK小组。义工也可以帮忙询问。", otherReply: "谢谢你告诉我们。这只是演示，不是实时求助服务。请向附近的社区中心查询；紧急情况请拨打求助电话。", verifiedWarning: "义工在演示中检查过这份餐食。出发前请向摊主确认仍有供应，并符合你的饮食要求；这不是独立保证。", expired: "这份餐食消息已过期，请不要特地前往。", withdrawn: "这份餐食已不再供应，请不要特地前往。"
  },
  ms: {
    greeting: "Hai jiran! Tanya tentang makanan lobang, acara CC, atau cari kawan untuk aktiviti kumpulan.", title: "Tanya tentang makanan, SMS atau berjalan kaki.", intro: "Hantar sahaja mesej.", demo: "CUBA MESEJ CONTOH", food: "Petua makanan", walk: "Cari kumpulan", cc: "Acara CC & Kampung", deals: "Lihat Tawaran Langsung", placeholder: "Taip mesej…", note: "Suara dikenal pasti oleh pelayar. Semak teks sebelum hantar.", send: "Hantar mesej", record: "Rakam mesej suara", stop: "Henti rakaman", diet: "Makanan untuk saya", all: "Semua Hidangan", halal: "Halal", vegetarian: "Vegetarian / Vegan", empty: "Tiada hidangan sesuai yang telah disemak. Jangan pergi kerana petua yang belum disahkan.", foodWarning: "Ini hanya petua makanan yang belum disahkan. Jangan pergi dahulu. Gambar gerai, lokasi dan semakan sukarelawan diperlukan. Sahkan harga, stok dan kesesuaian makanan terus dengan gerai.", walkReply: "Bagusnya! Tiada senarai acara langsung di sini. Sila tanya Kelab Masyarakat tentang kumpulan jalan, senamrobik, wushu, karaoke atau makan terkini sebelum pergi. Sukarelawan boleh membantu.", otherReply: "Terima kasih berkongsi. Ini hanya demo, bukan khidmat bantuan langsung. Semak dengan pusat masyarakat; jika kecemasan, hubungi bantuan kecemasan.", verifiedWarning: "Sukarelawan telah menyemak hidangan ini dalam demo. Sahkan stok dan kesesuaian makanan terus dengan gerai sebelum pergi. Ini bukan jaminan bebas.", expired: "Tawaran makanan ini telah tamat. Jangan pergi untuknya.", withdrawn: "Tawaran makanan ini tidak lagi tersedia. Jangan pergi untuknya."
  },
  ta: {
    greeting: "வணக்கம் அண்டைவீட்டாரே! மலிவு உணவு, சமூக மன்ற நிகழ்ச்சிகள், அல்லது குழு நடவடிக்கைகளுக்கு நண்பர்களைத் தேடுங்கள்.", title: "உணவு, செய்தி அல்லது நடைப்பயிற்சி பற்றி கேளுங்கள்.", intro: "ஒரு செய்தி அனுப்புங்கள்.", demo: "மாதிரி செய்தியை முயலுங்கள்", food: "உணவு தகவல்", walk: "நண்பர் குழு", cc: "சமூக மன்ற நிகழ்ச்சிகள்", deals: "நேரடி சலுகைகளைப் பார்", placeholder: "செய்தியை எழுதுங்கள்…", note: "குரலை உலாவி புரிந்துகொள்ளும். அனுப்புமுன் எழுத்தைச் சரிபாருங்கள்.", send: "செய்தி அனுப்பு", record: "குரல் பதிவு", stop: "பதிவை நிறுத்து", diet: "எனக்கான உணவு", all: "அனைத்து உணவுகள்", halal: "ஹலால்", vegetarian: "சைவம் / முழுச் சைவம்", empty: "பொருத்தமான சரிபார்க்கப்பட்ட உணவு இப்போது இல்லை. சரிபாராத தகவலுக்காகப் பயணம் செய்ய வேண்டாம்.", foodWarning: "இது சரிபார்க்கப்படாத உணவுத் தகவல் மட்டுமே. இப்போது செல்ல வேண்டாம். கடைப் படம், இடம், தன்னார்வலர் சோதனை தேவை. விலை, இருப்பு, உணவுப் பொருத்தம் ஆகியவற்றைக் கடையில் உறுதிசெய்யுங்கள்.", walkReply: "நல்ல யோசனை! நேரடி நிகழ்ச்சி பட்டியல் எங்களிடம் இல்லை. செல்லுமுன் சமூக மன்றத்தில் சமீபத்திய நடை, நடனப் பயிற்சி, வுஷூ, கராவோக்கே அல்லது மதிய உணவுக் குழுக்களைக் கேளுங்கள். தன்னார்வலர் உதவலாம்.", otherReply: "சொன்னதற்கு நன்றி. இது செயல்விளக்கமே; நேரடி உதவி சேவை அல்ல. அருகிலுள்ள சமூக மையத்தை அணுகுங்கள். அவசரத்தில் அவசர சேவையை அழையுங்கள்.", verifiedWarning: "இந்த செயல்விளக்கத்தில் தன்னார்வலர் உணவைச் சோதித்தார். செல்லுமுன் இருப்பையும் உணவுப் பொருத்தத்தையும் கடையில் உறுதிசெய்யுங்கள். இது தனித்த உறுதி அல்ல.", expired: "இந்த உணவுத் தகவல் காலாவதியானது. அதற்காகச் செல்ல வேண்டாம்.", withdrawn: "இந்த உணவு இனி கிடைக்காது. அதற்காகச் செல்ல வேண்டாம்."
  }
};
